# Tensorflow Insights

Agenda:

1.   Understand Tensorflow's computation graph approach
>*   What is Tensor? 
>*   What are the graphs?
4.   Explore Tensorflow's built-in functions and classes
>*   Basic operations
>*   Data types - constants
>*   Data types - variables
>*   Data types - placeholders
>*   The differences (tensorflow vs. standard python/pandas)



---

## Understand Tensorflow
### What is Tensor?


*   Multi-dimensional array
>*   0-d tensor: scalar (number)
>*   1-d tensor: vector
>*   2-d tensor: matrix

Importing the library

In [0]:
import tensorflow as tf

**Computational graph approach**
* Build the GRAPH which represents the data flow of the computation
* Run the SESSION which executes the operation on the graph

**Graph**
* Nodes = Operations
* Edges = Tensors

**Session**
* Tensor = data
* Tensor + flow = data + flow

In [4]:
a = 2
b = 3
c = tf.add(a, b, name='Add')
print(c)

with tf.Session() as sess:
  print(sess.run(c))


Tensor("Add:0", shape=(), dtype=int32)
5


## Explore Tensorflow

### Constants

Creating a constant in TensorFlow



In [0]:
# tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)
# constant of 1d tensor (vector)
a = tf.constant([2, 2], name="vector")
# constant of 2x2 tensor (matrix)
b = tf.constant([[0, 1], [2, 3]], name="matrix")


You can create a tensor of a specific dimension and fill it with a specific value, similar to Numpy.


In [7]:

# tf.zeros(shape, dtype=tf.float32, name=None)
# create a tensor of shape and all elements are zeros
tf.zeros([2, 3], tf.int32) # ==> [[0, 0, 0], [0, 0, 0]]


<tf.Tensor 'zeros:0' shape=(2, 3) dtype=int32>

In [11]:

# tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)
# create a tensor of shape and type (unless type is specified) as the input_tensor but all elements are zeros.
input_tensor = [[0, 1], [2, 3], [4, 5]]
tf.zeros_like(input_tensor) # ==> [[0, 0], [0, 0], [0, 0]]


<tf.Tensor 'zeros_like:0' shape=(3, 2) dtype=int32>

In [0]:

# tf.ones(shape, dtype=tf.float32, name=None)
# create a tensor of shape and all elements are ones
tf.ones([2, 3], tf.int32) #==> [[1, 1, 1], [1, 1, 1]]


In [0]:

# tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)
# create a tensor of shape and type (unless type is specified) as the input_tensor but all elements are ones.
# input_tensor is [[0, 1], [2, 3], [4, 5]]
tf.ones_like(input_tensor) #==> [[1, 1], [1, 1], [1, 1]]


In [0]:

# tf.fill(dims, value, name=None) 
# create a tensor filled with a scalar value.
tf.fill([2, 3], 8) #==> [[8, 8, 8], [8, 8, 8]]


You can create constants that are sequences

In [0]:

# tf.lin_space(start, stop, num, name=None)
# create a sequence of num evenly-spaced values are generated beginning at start. If num > 1, the values in the sequence increase by (stop - start) / (num - 1), so that the last one is exactly stop.
# comparable to but slightly different from numpy.linspace

tf.lin_space(10.0, 13.0, 4, name="linspace") #==> [10.0 11.0 12.0 13.0]


In [0]:
# tf.range([start], limit=None, delta=1, dtype=None, name='range')
# create a sequence of numbers that begins at start and extends by increments of delta up to but not including limit
# slight different from range in Python
start = 3
limit = 18
delta = 3
# 'start' is 3, 'limit' is 18, 'delta' is 3
tf.range(start, limit, delta) #==> [3, 6, 9, 12, 15]
start = 3
limit = 1
delta = -0.5
# 'start' is 3, 'limit' is 1,  'delta' is -0.5
tf.range(start, limit, delta) #==> [3, 2.5, 2, 1.5]
limit = 5
# 'limit' is 5
tf.range(limit) ==> [0, 1, 2, 3, 4]


**Note** unlike NumPy or Python sequences, TensorFlow **sequences are not iterable**.

You can also generate random constants from certain distributions

In [0]:

#tf.random_normal
#tf.truncated_normal
#tf.random_uniform
#tf.random_shuffle
#tf.random_crop
#tf.multinomial
#tf.random_gamma
#tf.set_random_seed


### Math Operations

Be sure to read documentation to decide which division to use. tf.divide does exactly Python style division.

In [12]:
import tensorflow as tf
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
with tf.Session() as sess:
  print(sess.run(tf.div(b, a)))             
  print(sess.run(tf.divide(b, a)))
  print(sess.run(tf.truediv(b, a)))
  print(sess.run(tf.floordiv(b, a)))
  #print(sess.run(tf.realdiv(b, a))) Gives error only works for real values
  print(sess.run(tf.truncatediv(b, a)))
  print(sess.run(tf.floor_div(b, a)))  

[[0 0]
 [1 1]]
[[0.  0.5]
 [1.  1.5]]
[[0.  0.5]
 [1.  1.5]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]


tf.add_n allows adding multiple tensors

tf.add_n([a,b,b]) equivalent to a + b + b

Dot product in TensorFlow

In [13]:
a = tf.constant([10, 20], name='a')
b = tf.constant([2, 3], name='b')
with tf.Session() as sess:
	print(sess.run(tf.multiply(a, b)))           
	print(sess.run(tf.tensordot(a, b, 1)))

[20 60]
80


![alt text](https://tensorflowOperations)
### Python native types vs. TensorFlow native types

TensorFlow takes in Python native types such as 

* boolean values, numeric values (integers, floats), and strings

Single values will be converted to 0-d tensors (or scalars)

In [0]:
t_0 = 19 # Treated as a 0-d tensor, or "scalar" 
tf.zeros_like(t_0) # ==> 0
tf.ones_like(t_0) # ==> 1


Lists of values will be converted to 1-d tensors (vectors)

In [0]:
t_1 = [b"apple", b"peach", b"grape"] # treated as a 1-d tensor, or "vector"
tf.zeros_like(t_1)                   # ==> [b'' b'' b'']
tf.ones_like(t_1)                    # ==> TypeError



Lists of lists of values will be converted to 2-d tensors (matrices)


In [0]:
t_2 = [[True, False, False],
       [False, False, True],
       [False, True, False]]         # treated as a 2-d tensor, or "matrix"

tf.zeros_like(t_2)                   # ==> 3x3 tensor, all elements are False
tf.ones_like(t_2)                    # ==> 3x3 tensor, all elements are True



![alt text](https://tfNativeTypes)

TensorFlow was designed to integrate seamlessly with Numpy


In [0]:
tf.ones([2, 2], np.float32) #==> [[1.0 1.0], [1.0 1.0]]

Most of the times, you can use TensorFlow types and NumPy types interchangeably

**Note** 
* tf.string does not have an exact match in NumPy due to the way NumPy handles strings - TensorFlow can still import string arrays from NumPy perfectly fine -- just don't specify a dtype in NumPy!

* Both TensorFlow and NumPy are n-d array libraries. NumPy supports ndarray, but doesn't offer methods to create tensor functions and automatically compute derivatives, nor GPU support. TensorFlow does support GPU.

* Python types lack the ability to explicitly state the data type, while TensorFlow's data types are more explicit.e.g Python all integers are of the same type tf has 8-bit, 16-bit, 32-bit, and 64-bit integers available.

* Although it is possible to define Tensor objects as NumPy arrays - always use TensorFlow types when possible.

### Variables

When constants are memory expensive, such as a weight matrix with millions of entries, it will be slow each time you have to load the graph. To see what’s stored in the graph's definition, simply print out the graph's protobuf. Protobuf stands for protocol buffer, 



In [0]:
import tensorflow as tf

my_const = tf.constant([1.0, 2.0], name="my_const")
print(tf.get_default_graph().as_graph_def())

To **declare** a variable, you create an instance of the class tf.Variable. Variable is a class with multiple operations

* x = tf.Variable(...) 
* x.initializer # init 
* x.value() # read op 
* x.assign(...) # write op 
* x.assign_add(...) 

The old way to create a variable is simply call tf.Variable(<initial-value>, name=<optional-name>)


In [0]:
s = tf.Variable(2, name="scalar") 
m = tf.Variable([[0, 1], [2, 3]], name="matrix") 
W = tf.Variable(tf.zeros([784,10]))

 this old way is discouraged and TensorFlow recommends that we use the wrapper tf.get_variable, which allows for easy variable sharing

In [0]:
tf.get_variable(
    name,
    shape=None,
    dtype=None,
    initializer=None,
    regularizer=None,
    trainable=True,
    collections=None,
    caching_device=None,
    partitioner=None,
    validate_shape=True,
    use_resource=None,
    custom_getter=None,
    constraint=None
)


In [0]:
s = tf.get_variable("scalar", initializer=tf.constant(2)) 
m = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())

You have to **initialize** a variable before using it.

To get a list of uninitialized variables, you can just print them out:


In [0]:
print(session.run(tf.report_uninitialized_variables()))

The easiest way is initialize all variables at once

In [0]:
with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())

In this case, you use tf.Session.run() to fetch an initializer op, not a tensor op like we have used it previously.

To initialize only a subset of variables, you use tf.variables_initializer() with a list of variables you want to initialize:


In [0]:
with tf.Session() as sess:
	sess.run(tf.variables_initializer([a, b]))

You can also initialize each variable separately using tf.Variable.initializer

In [0]:
with tf.Session() as sess:
	sess.run(W.initializer)

Another way to initialize a variable is to load its value from a file

To **evaluate** the variable we need to fetch it within a session

In [0]:
# V is a 784 x 10 variable of random values
V = tf.get_variable("normal_matrix", shape=(784, 10), 
                     initializer=tf.truncated_normal_initializer())

with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())
	print(sess.run(V))

You can also get a variable’s value from tf.Variable.eval()


In [0]:
with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())
  print(V.eval())

To **assign** a value to a variable use tf.Variable.assign()

In [0]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
	sess.run(W.initializer)
	print(W.eval()) # >> 10

Why 10 and not 100? W.assign(100) doesn't assign the value 100 to W, but instead create an assign op to do that. For this op to take effect, we have to run this op in session. 

In [0]:
W = tf.Variable(10)

assign_op = W.assign(100)
with tf.Session() as sess:
	sess.run(assign_op)
	print(W.eval()) # >> 100

Note that we don't have to initialize W in this case, because assign() does it for us. In fact, the initializer op is an assign op that assigns the variable's initial value to the variable itself.


In [0]:
# in the source code
self._initializer_op = state_ops.assign(self._variable, self._initial_value,
                                        validate_shape=validate_shape).op

Interesting example:

In [0]:
# create a variable whose original value is 2
a = tf.get_variable('scalar', initializer=tf.constant(2)) 
a_times_two = a.assign(a * 2)
with tf.Session() as sess:
	sess.run(tf.global_variables_initializer()) 
	sess.run(a_times_two) # >> 4
	sess.run(a_times_two) # >> 8
	sess.run(a_times_two) # >> 16

Simply incrementing, decrementing a variable

In [0]:
W = tf.Variable(10)

with tf.Session() as sess:
	sess.run(W.initializer)
	print(sess.run(W.assign_add(10))) # >> 20
	print(sess.run(W.assign_sub(2)))  # >> 18

TensorFlow sessions maintain values separately, therefore each Session can have its own current value for a variable defined in a graph.

In [0]:
W = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()
sess1.run(W.initializer)
sess2.run(W.initializer)
print(sess1.run(W.assign_add(10)))		# >> 20
print(sess2.run(W.assign_sub(2)))		# >> 8
print(sess1.run(W.assign_add(100)))		# >> 120
print(sess2.run(W.assign_sub(50)))		# >> -42
sess1.close()
sess2.close()

suppose you want to declare U = W * 2

In [0]:
# W is a random 700 x 10 tensor
W = tf.Variable(tf.truncated_normal([700, 10]))
U = tf.Variable(W * 2)

In this case, you should use initialized_value() to make sure that W is initialized before its value is used to initialize U.


In [0]:
U = tf.Variable(W.initialized_value() * 2)

### Interactive session

In [0]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
print(c.eval()) # we can use 'c.eval()' without explicitly stating a session
sess.close()

### Control Dependencies

Sometimes, we have two or more independent ops and we'd like to specify which ops should be run first. In this case, we use tf.Graph.control_dependencies([control_inputs]).


In [0]:
# your graph g have 5 ops: a, b, c, d, e
with g.control_dependencies([a, b, c]):
  # `d` and `e` will only run after `a`, `b`, and `c` have executed.
  d = ...
  e = …